---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgdata-pvc-hdd
  namespace: hw5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-ceph-hdd-dp1
